apiVersion: v1
kind: Service
metadata:
  name: login-portal-web
  namespace: login-portal

spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app: login-portal-web
    release: {{ .Release.Name }}
  sessionAffinity: None
  type: NodePort
